  RequestValidatorOnlyBody:
    Type: "AWS::ApiGateway::RequestValidator"
    Properties:
      Name: 'only-body'
      RestApiId:
        Ref: ApiGatewayRestApi
      ValidateRequestBody: true
      ValidateRequestParameters: false
  RequestValidatorOnlyParameters:
      Type: "AWS::ApiGateway::RequestValidator"
      Properties:
        Name: 'only-parameters'
        RestApiId:
          Ref: ApiGatewayRestApi
        ValidateRequestBody: false
        ValidateRequestParameters: true
