Resources:
  ######################
  ## S3
  ######################
  BUCKET:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: websitebucket
      AccessControl: Private
      VersioningConfiguration:
          Status: Enabled
  BUCKETPOLICY:
    Type: AWS::S3::BucketPolicy
    Properties:
      Bucket:
        Ref: BUCKET
      PolicyDocument:
        Statement:
        - Action:
          - s3:GetObject
          Effect: Allow
          Resource:
            Fn::Join:
            - ""
            -
              - "arn:aws:s3:::"
              - Ref: BUCKET
              - "/*"
          Principal:
            CanonicalUser:
              Fn::GetAtt: CLOUDFRONTORIGINACCESSIDENTITY.S3CanonicalUserId
  ######################
  ## CloudFront
  ######################
  CLOUDFRONTORIGINACCESSIDENTITY:
    Type: AWS::CloudFront::CloudFrontOriginAccessIdentity
    Properties:
      CloudFrontOriginAccessIdentityConfig:
        Comment: "Website"
  CLOUDFRONTDISTRIBUTION:
    Type: AWS::CloudFront::Distribution
    Properties:
      DistributionConfig:
        Aliases:
          - app1.terra10.io
        DefaultCacheBehavior:
          Compress: true
          ForwardedValues:
            QueryString: false
          TargetOriginId: s3-terra10-origin
          ViewerProtocolPolicy: redirect-
          to-https
        DefaultRootObject: index.html
        CustomErrorResponses:
        - ErrorCachingMinTTL: 300
          ErrorCode: 403
          ResponseCode: 200
          ResponsePagePath: /index.html
        - ErrorCachingMinTTL: 300
          ErrorCode: 404
          ResponseCode: 200
          ResponsePagePath: /index.html
        Enabled: true
        HttpVersion: http2
        Origins:
        - DomainName:
            Fn::Join:
            - ""
            - - Ref: BUCKET
              - ".s3.amazonaws.com"
          Id: s3-terra10-origin
          S3OriginConfig:
            OriginAccessIdentity:
              Fn::Join:
              - ""
              - - "origin-access-identity/cloudfront/"
                - Ref: CLOUDFRONTORIGINACCESSIDENTITY
        PriceClass: PriceClass_100
        ViewerCertificate:
          AcmCertificateArn: arn:aws:acm:us-east-1:XXXXXXX:certificate/YYYYYYYYY
          MinimumProtocolVersion: TLSv1.1_2016
          SslSupportMethod: sni-only
