## Basic DynamoDB table with
## - on-demand scaling so no read/write request
## KMS/Encryption at rest
## DelitionPolicy just to be sure
DDBTable:
  Type: "AWS::DynamoDB::Table"
  DeletionPolicy: Retain
  Properties:
    TableName: MyDynamoDBTable
    SSESpecification:
      SSEEnabled: true
    PointInTimeRecoverySpecification:
      PointInTimeRecoveryEnabled: true
    AttributeDefinitions:
    -
      AttributeName: "myidentification"
      AttributeType: "S"
    KeySchema:
    -
      AttributeName: "myidentification"
      KeyType: "HASH"
    BillingMode: PAY_PER_REQUEST
